# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

## Ex 1-1 Installing numpy

In [5]:
!pip install numpy

## Ex 1-2 Importing numpy

In [6]:
import numpy as np

## Ex 1-3 Example

In [7]:
data = np.array([1,2,3,4,5])

In [8]:
print(data)

[1 2 3 4 5]


In [9]:
print(len(data))

5


In [10]:
print(type(data))

<class 'numpy.ndarray'>


In [11]:
print(data.shape)

(5,)


## Ex 1-4 Exercise from lecture slides

In [12]:
# Example 1- Creating an array
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [13]:
# Example 2- Creating a 2D array
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [14]:
# Example 3- Array indexing
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [15]:
# Example 4- Slicing in an array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [16]:
# Example 5- Sorting the array
arr = np.array([30, 40, 20, 10])
print(np.sort(arr))

[10 20 30 40]


In [17]:
# Example 6- Sorting array alphabetically
arr= np.array(['kiwi', 'berry', 'grapes', 'apple'])
print(np.sort(arr))

['apple' 'berry' 'grapes' 'kiwi']


## Ex 1-5 Searching arrays

In [18]:
arr = np.array([3, 2, 14, 9, 10, 12])

In [19]:
x = np.where(arr == 9)

In [20]:
print(x)

(array([3], dtype=int64),)


## Ex 1-6 Joining arrays

In [21]:
arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

In [22]:
# Join the arrays
result = np.concatenate((arr1, arr2))

In [23]:
# Print the result
print("Joined array:", result)

Joined array: [ 9  5  8 55 89 76]


In [24]:
# Or we can also write as
print(result)

[ 9  5  8 55 89 76]
